-- AHMED ELGHRBAWY FINAL SUPABASE SCHEMA
-- Run this whole file once in Supabase SQL Editor.
create extension if not exists pgcrypto;

do $$ begin create type public.user_role as enum ('student','admin'); exception when duplicate_object then null; end $$;
do $$ begin create type public.content_type as enum ('video','image','exam'); exception when duplicate_object then null; end $$;
do $$ begin create type public.purchase_status as enum ('pending','approved','rejected'); exception when duplicate_object then null; end $$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default 'طالب جديد', login_email text unique, phone text unique,
  stage text, grade text, account_type text not null default 'student' check(account_type in ('student','teacher','admin')), role public.user_role not null default 'student',
  xp integer not null default 0 check (xp >= 0), created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
alter table public.profiles add column if not exists account_type text not null default 'student';
alter table public.profiles drop constraint if exists profiles_account_type_check;
alter table public.profiles add constraint profiles_account_type_check check(account_type in ('student','teacher','admin'));

create table if not exists public.content (
  id bigint generated by default as identity primary key,
  type public.content_type not null, title text not null, description text default '',
  price numeric(10,2) not null default 0 check(price>=0), is_free boolean not null default true,
  stage text, grade text, storage_path text, thumbnail_path text, external_url text, created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.exams (
  id bigint generated by default as identity primary key, title text not null, description text default '', stage text, grade text,
  is_published boolean not null default false, created_by uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now()
);
create table if not exists public.exam_questions (
  id bigint generated by default as identity primary key, exam_id bigint not null references public.exams(id) on delete cascade,
  question text not null, options jsonb not null, correct_index integer not null check(correct_index>=0), sort_order integer not null default 0
);
create table if not exists public.purchases (
  id bigint generated by default as identity primary key, student_id uuid not null references public.profiles(id) on delete cascade,
  content_id bigint not null references public.content(id) on delete cascade, status public.purchase_status not null default 'pending',
  amount numeric(10,2) not null default 0 check(amount>=0), created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  unique(student_id,content_id)
);
create table if not exists public.results (
  id bigint generated by default as identity primary key, student_id uuid not null references public.profiles(id) on delete cascade,
  exam_id bigint not null references public.exams(id) on delete cascade, score integer not null, total integer not null,
  percentage numeric(5,2) not null, answers jsonb not null default '[]'::jsonb, created_at timestamptz not null default now()
);

create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles where id=auth.uid() and role='admin'); $$;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,full_name,login_email,phone,stage,grade,account_type) values(new.id,coalesce(new.raw_user_meta_data->>'full_name','طالب جديد'),new.email,null,new.raw_user_meta_data->>'stage',new.raw_user_meta_data->>'grade',coalesce(new.raw_user_meta_data->>'account_type','student')) on conflict(id) do nothing; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users; create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create or replace function public.protect_student_profile() returns trigger language plpgsql security definer set search_path=public as $$
begin
  if auth.uid() = old.id and not public.is_admin() then
    new.role := old.role;
    new.xp := old.xp;
    new.id := old.id;
    new.phone := old.phone;
    new.login_email := old.login_email;
    new.account_type := old.account_type;
  end if;
  return new;
end; $$;
drop trigger if exists protect_student_profile on public.profiles;
create trigger protect_student_profile before update on public.profiles for each row execute procedure public.protect_student_profile();

create or replace function public.touch_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end; $$;
drop trigger if exists profiles_touch on public.profiles; create trigger profiles_touch before update on public.profiles for each row execute procedure public.touch_updated_at();
drop trigger if exists content_touch on public.content; create trigger content_touch before update on public.content for each row execute procedure public.touch_updated_at();
drop trigger if exists purchases_touch on public.purchases; create trigger purchases_touch before update on public.purchases for each row execute procedure public.touch_updated_at();

alter table public.profiles enable row level security; alter table public.content enable row level security; alter table public.exams enable row level security; alter table public.exam_questions enable row level security; alter table public.purchases enable row level security; alter table public.results enable row level security;

-- profiles
 drop policy if exists profiles_select on public.profiles; create policy profiles_select on public.profiles for select to authenticated using(id=auth.uid() or public.is_admin());
drop policy if exists profiles_update on public.profiles; create policy profiles_update on public.profiles for update to authenticated using(id=auth.uid() or public.is_admin()) with check(id=auth.uid() or public.is_admin());
drop policy if exists profiles_admin_all on public.profiles; create policy profiles_admin_all on public.profiles for all to authenticated using(public.is_admin()) with check(public.is_admin());
-- students can see content metadata, but files are protected by storage policies
 drop policy if exists content_select on public.content; create policy content_select on public.content for select to authenticated using(true);
drop policy if exists content_admin on public.content; create policy content_admin on public.content for all to authenticated using(public.is_admin()) with check(public.is_admin());
-- exams: students only published
 drop policy if exists exams_select on public.exams; create policy exams_select on public.exams for select to authenticated using(is_published or public.is_admin());
drop policy if exists exams_admin on public.exams; create policy exams_admin on public.exams for all to authenticated using(public.is_admin()) with check(public.is_admin());
-- question table is ADMIN ONLY; students use RPC below, so correct answers never reach browser
 drop policy if exists questions_admin on public.exam_questions; create policy questions_admin on public.exam_questions for all to authenticated using(public.is_admin()) with check(public.is_admin());
-- purchases
 drop policy if exists purchases_select on public.purchases; create policy purchases_select on public.purchases for select to authenticated using(student_id=auth.uid() or public.is_admin());
drop policy if exists purchases_insert on public.purchases; create policy purchases_insert on public.purchases for insert to authenticated with check(student_id=auth.uid());
drop policy if exists purchases_update_admin on public.purchases; create policy purchases_update_admin on public.purchases for update to authenticated using(public.is_admin()) with check(public.is_admin());
-- results: students read own; INSERT/score calculation is ONLY through RPC
 drop policy if exists results_select on public.results; create policy results_select on public.results for select to authenticated using(student_id=auth.uid() or public.is_admin());
drop policy if exists results_admin on public.results; create policy results_admin on public.results for all to authenticated using(public.is_admin()) with check(public.is_admin());

create or replace function public.get_exam_questions(p_exam_id bigint)
returns table(id bigint,question text,options jsonb,sort_order integer)
language plpgsql security definer set search_path=public as $$
begin
 if not exists(select 1 from public.exams where public.exams.id=p_exam_id and is_published=true) and not public.is_admin() then raise exception 'Exam is not available'; end if;
 return query select q.id,q.question,q.options,q.sort_order from public.exam_questions q where q.exam_id=p_exam_id order by q.sort_order,q.id;
end; $$;
revoke all on function public.get_exam_questions(bigint) from public; grant execute on function public.get_exam_questions(bigint) to authenticated;

create or replace function public.submit_exam(p_exam_id bigint,p_answers jsonb)
returns bigint language plpgsql security definer set search_path=public as $$
declare qcount integer; score integer:=0; i integer; answer integer; rid bigint; total integer; pct numeric; rec record;
begin
 if auth.uid() is null then raise exception 'Not authenticated'; end if;
 if exists(select 1 from public.results where student_id=auth.uid() and exam_id=p_exam_id) then raise exception 'You have already submitted this exam'; end if;
 if not exists(select 1 from public.exams where id=p_exam_id and is_published=true) then raise exception 'Exam is not available'; end if;
 select count(*) into qcount from public.exam_questions where exam_id=p_exam_id;
 if qcount=0 then raise exception 'Exam has no questions'; end if;
 total:=qcount;
 i:=0;
 for rec in (select correct_index from public.exam_questions where exam_id=p_exam_id order by sort_order,id) loop
   answer:=nullif((p_answers->>i),'')::integer;
   if answer is not null and answer=rec.correct_index then score:=score+1; end if;
   i:=i+1;
 end loop;
 pct:=round((score::numeric/total::numeric)*100,2);
 insert into public.results(student_id,exam_id,score,total,percentage,answers) values(auth.uid(),p_exam_id,score,total,pct,p_answers) returning id into rid;
 update public.profiles set xp=xp+(score*10) where id=auth.uid();
 return rid;
end; $$;
revoke all on function public.submit_exam(bigint,jsonb) from public; grant execute on function public.submit_exam(bigint,jsonb) to authenticated;

-- storage
insert into storage.buckets(id,name,public) values('content','content',false) on conflict(id) do nothing;
drop policy if exists content_storage_read on storage.objects;
create policy content_storage_read on storage.objects for select to authenticated using(bucket_id='content' and (public.is_admin() or exists(select 1 from public.content c where c.storage_path=name and (c.is_free or exists(select 1 from public.purchases p where p.content_id=c.id and p.student_id=auth.uid() and p.status='approved')))));
drop policy if exists content_storage_insert on storage.objects; create policy content_storage_insert on storage.objects for insert to authenticated with check(bucket_id='content' and public.is_admin());
drop policy if exists content_storage_update on storage.objects; create policy content_storage_update on storage.objects for update to authenticated using(bucket_id='content' and public.is_admin()) with check(bucket_id='content' and public.is_admin());
drop policy if exists content_storage_delete on storage.objects; create policy content_storage_delete on storage.objects for delete to authenticated using(bucket_id='content' and public.is_admin());

-- الطالب يختار أي مرحلة من المراحل الثلاث الموجودة في الواجهة: ابتدائية / إعدادية / ثانوية.
-- account_type is only a label selected at registration; it NEVER grants admin privileges. Only role='admin' grants admin access.
-- First admin: create the account from the website, then find its id with:
-- select id, full_name, login_email from public.profiles order by created_at desc;
-- Then promote it:
-- update public.profiles set role='admin' where id='PASTE-USER-ID-HERE';

-- V3 platform settings + activity logs + public support cards
create table if not exists public.site_settings (
  id integer primary key default 1 check (id=1),
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);
insert into public.site_settings(id,data) values (1, jsonb_build_object(
  'hero_title','الفيزياء مش حفظ… الفيزياء فهم.',
  'hero_subtitle','افهم القانون، شوف الفكرة، وبعدها الحل هييجي لوحده.',
  'teacher_phone','',
  'teacher_image','',
  'support_phone','01105638650',
  'developer_phone','01105638650',
  'whatsapp','',
  'tiktok','',
  'youtube','',
  'background_image','',
  'music_enabled',true,
  'helper_name','HELPER',
  'helper_title','مساعدة ودعم الطلاب',
  'helper_phone','',
  'helper_image','',
  'admin_name','ADMIN',
  'admin_title','إدارة المنصة',
  'admin_phone','',
  'admin_image','',
  'discord_webhook',''
)) on conflict(id) do nothing;
alter table public.site_settings enable row level security;
drop policy if exists site_settings_public on public.site_settings;
create policy site_settings_public on public.site_settings for select to anon, authenticated using(true);
drop policy if exists site_settings_admin on public.site_settings;
create policy site_settings_admin on public.site_settings for all to authenticated using(public.is_admin()) with check(public.is_admin());

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  event_type text not null,
  actor_id uuid references public.profiles(id) on delete set null,
  target_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.activity_logs enable row level security;
drop policy if exists activity_logs_admin on public.activity_logs;
create policy activity_logs_admin on public.activity_logs for all to authenticated using(public.is_admin()) with check(public.is_admin());
-- Public browsing: visitors can see cards/metadata, but protected files/exams remain locked until login.
drop policy if exists content_public_select on public.content;
create policy content_public_select on public.content for select to anon using(true);
drop policy if exists exams_public_select on public.exams;
create policy exams_public_select on public.exams for select to anon using(is_published=true);

-- Prevent a student from submitting the same exam more than once.
create unique index if not exists results_one_attempt on public.results(student_id, exam_id);

-- Automatic activity log entries for the main platform actions.
create or replace function public.log_activity_change() returns trigger language plpgsql security definer set search_path=public as $$
declare actor uuid; rowj jsonb; target text; display_name text;
begin
  actor := auth.uid();
  rowj := case when TG_OP='DELETE' then to_jsonb(old) else to_jsonb(new) end;
  target := coalesce(rowj->>'id','');
  display_name := coalesce(rowj->>'full_name',rowj->>'title',rowj->>'status','');
  insert into public.activity_logs(event_type,actor_id,target_id,details)
  values (TG_TABLE_NAME||':'||lower(TG_OP), actor, target, jsonb_build_object('table',TG_TABLE_NAME,'operation',TG_OP,'name',display_name));
  return case when TG_OP='DELETE' then old else new end;
end; $$;
drop trigger if exists profiles_activity_log on public.profiles; create trigger profiles_activity_log after insert or update or delete on public.profiles for each row execute procedure public.log_activity_change();
drop trigger if exists content_activity_log on public.content; create trigger content_activity_log after insert or update or delete on public.content for each row execute procedure public.log_activity_change();
drop trigger if exists exams_activity_log on public.exams; create trigger exams_activity_log after insert or update or delete on public.exams for each row execute procedure public.log_activity_change();
drop trigger if exists results_activity_log on public.results; create trigger results_activity_log after insert or update or delete on public.results for each row execute procedure public.log_activity_change();
drop trigger if exists purchases_activity_log on public.purchases; create trigger purchases_activity_log after insert or update or delete on public.purchases for each row execute procedure public.log_activity_change();

-- Public brand assets (backgrounds / logos) managed from Admin settings.
insert into storage.buckets(id,name,public) values('site-assets','site-assets',true) on conflict(id) do update set public=true;
drop policy if exists site_assets_admin_insert on storage.objects;
create policy site_assets_admin_insert on storage.objects for insert to authenticated with check(bucket_id='site-assets' and public.is_admin());
drop policy if exists site_assets_admin_update on storage.objects;
create policy site_assets_admin_update on storage.objects for update to authenticated using(bucket_id='site-assets' and public.is_admin()) with check(bucket_id='site-assets' and public.is_admin());
drop policy if exists site_assets_admin_delete on storage.objects;
create policy site_assets_admin_delete on storage.objects for delete to authenticated using(bucket_id='site-assets' and public.is_admin());

-- V4 media migration: video/image thumbnails
alter table public.content add column if not exists thumbnail_path text;
insert into storage.buckets(id,name,public) values('content-thumbnails','content-thumbnails',true) on conflict(id) do update set public=true;
drop policy if exists content_thumbnails_public_read on storage.objects;
create policy content_thumbnails_public_read on storage.objects for select to public using(bucket_id='content-thumbnails');
drop policy if exists content_thumbnails_admin_insert on storage.objects;
create policy content_thumbnails_admin_insert on storage.objects for insert to authenticated with check(bucket_id='content-thumbnails' and public.is_admin());
drop policy if exists content_thumbnails_admin_update on storage.objects;
create policy content_thumbnails_admin_update on storage.objects for update to authenticated using(bucket_id='content-thumbnails' and public.is_admin()) with check(bucket_id='content-thumbnails' and public.is_admin());
drop policy if exists content_thumbnails_admin_delete on storage.objects;
create policy content_thumbnails_admin_delete on storage.objects for delete to authenticated using(bucket_id='content-thumbnails' and public.is_admin());


-- V5 FINAL FIX: password-only UI + phone info + activity tracking + Discord settings
alter table public.profiles drop constraint if exists profiles_phone_key;
alter table public.profiles add column if not exists password_lookup text;
create unique index if not exists profiles_password_lookup_unique on public.profiles(password_lookup) where password_lookup is not null;

-- Store phone during Auth trigger when supplied; never expose the internal Auth email in the UI.
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.profiles(id,full_name,login_email,phone,stage,grade,account_type)
  values(new.id,coalesce(new.raw_user_meta_data->>'full_name','طالب جديد'),new.email,nullif(new.raw_user_meta_data->>'phone',''),new.raw_user_meta_data->>'stage',new.raw_user_meta_data->>'grade',coalesce(new.raw_user_meta_data->>'account_type','student'))
  on conflict(id) do update set full_name=excluded.full_name,phone=excluded.phone,stage=excluded.stage,grade=excluded.grade,account_type=excluded.account_type;
  return new;
end; $$;

-- Students may create their own activity events through this controlled RPC only.
create or replace function public.log_user_activity(p_event_type text,p_target_id text default '',p_details jsonb default '{}'::jsonb)
returns bigint language plpgsql security definer set search_path=public as $$
declare rid bigint;
begin
  if auth.uid() is null then raise exception 'Not authenticated'; end if;
  insert into public.activity_logs(event_type,actor_id,target_id,details) values(p_event_type,auth.uid(),p_target_id,coalesce(p_details,'{}'::jsonb)) returning id into rid;
  return rid;
end; $$;
revoke all on function public.log_user_activity(text,text,jsonb) from public;
grant execute on function public.log_user_activity(text,text,jsonb) to authenticated;

-- Add richer Discord room configuration without exposing bot secrets to the browser.
update public.site_settings set data = data || jsonb_build_object(
  'discord_webhook_registrations',coalesce(data->>'discord_webhook_registrations',''),
  'discord_webhook_videos',coalesce(data->>'discord_webhook_videos',''),
  'discord_webhook_images',coalesce(data->>'discord_webhook_images',''),
  'discord_webhook_exams',coalesce(data->>'discord_webhook_exams',''),
  'discord_webhook_admin',coalesce(data->>'discord_webhook_admin',''),
  'discord_webhook_members',coalesce(data->>'discord_webhook_members',''),
  'discord_guild_id',coalesce(data->>'discord_guild_id','')
),updated_at=now() where id=1;

-- Registration logs are generated by the backend/API after successful account creation.
