(async()=>{
 const user=await window.requireAuth();if(!user)return;const sb=window.elrfaeySupabase,grid=document.getElementById('contentGrid');let items=[];let approved=new Set();
 const {data:purchases}=await sb.from('purchases').select('content_id,status').eq('student_id',user.id);(purchases||[]).filter(x=>x.status==='approved').forEach(x=>approved.add(String(x.content_id)));
 const [cr,er]=await Promise.all([sb.from('content').select('id,type,title,description,price,is_free,stage,grade,storage_path,external_url,created_at').order('created_at',{ascending:false}),sb.from('exams').select('id,title,description,stage,grade,created_at').eq('is_published',true).order('created_at',{ascending:false})]);if(cr.error){grid.innerHTML='<p>تعذر تحميل المحتوى.</p>';return}const normal=cr.data||[];const examItems=(er.data||[]).map(x=>({id:'exam-'+x.id,exam_id:x.id,type:'exam',title:x.title,description:x.description,price:0,is_free:true,stage:x.stage,grade:x.grade,created_at:x.created_at}));items=[...normal,...examItems].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));
 function youtubeEmbed(url){try{const u=new URL(url);let id=u.searchParams.get('v');if(!id&&u.hostname.includes('youtu.be'))id=u.pathname.slice(1);if(!id&&u.pathname.includes('/shorts/'))id=u.pathname.split('/shorts/')[1].split(/[?&]/)[0];return id?`https://www.youtube.com/embed/${id}?autoplay=1&rel=0`:null}catch(e){return null}}
 window.openContent=async id=>{const item=items.find(x=>String(x.id)===String(id));if(!item)return;if(item.type==='exam'){location.href=`exam.html?id=${item.exam_id}`;return}if(!item.is_free&&!approved.has(String(item.id))){window.toast('هذا المحتوى غير مفتوح لحسابك.',false);return}
  if(item.external_url){const emb=item.type==='video'?youtubeEmbed(item.external_url):null;if(emb){const modal=document.createElement('div');modal.className='media-modal';modal.innerHTML=`<div class="media-modal-box"><button class="media-close">×</button><iframe src="${emb}" title="${window.ELR.escape(item.title)}" allow="autoplay; encrypted-media; picture-in-picture" allowfullscreen></iframe></div>`;document.body.appendChild(modal);modal.querySelector('.media-close').onclick=()=>modal.remove();modal.onclick=e=>{if(e.target===modal)modal.remove()};}else if(item.type==='image'){const modal=document.createElement('div');modal.className='media-modal';modal.innerHTML=`<div class="media-modal-box image-box"><button class="media-close">×</button><img src="${window.ELR.escape(item.external_url)}" alt="${window.ELR.escape(item.title)}"></div>`;document.body.appendChild(modal);modal.querySelector('.media-close').onclick=()=>modal.remove();modal.onclick=e=>{if(e.target===modal)modal.remove()};}else location.href=item.external_url;return}
  if(!item.storage_path){window.toast('المحتوى لا يحتوي على ملف أو رابط.',false);return}const {data:s,error:e}=await sb.storage.from('content').createSignedUrl(item.storage_path,600);if(e||!s?.signedUrl){window.toast('تعذر فتح الملف: '+(e?.message||''),false);return}window.open(s.signedUrl,'_blank');
 };
 window.requestBuy=async id=>{const item=items.find(x=>String(x.id)===String(id));if(!item)return;const {error:e}=await sb.from('purchases').upsert({student_id:user.id,content_id:item.id,amount:item.price,status:'pending'},{onConflict:'student_id,content_id'});if(e){window.toast('تعذر إرسال الطلب: '+e.message,false);return}window.toast('تم إرسال طلب فتح المحتوى للإدارة.');approved.delete(String(item.id));render(current)};
 let current='all';function render(type){current=type;const icons={video:'🎥',image:'🖼️',exam:'📝'},labels={video:'فيديو',image:'صورة',exam:'امتحان'};const list=items.filter(x=>type==='all'||x.type===type);grid.innerHTML=list.map(x=>{const can=x.is_free||approved.has(String(x.id));const action=can?`<button class="btn btn-primary small" onclick='openContent(${JSON.stringify(String(x.id))})'>فتح</button>`:`<button class="btn btn-ghost small" onclick='requestBuy(${JSON.stringify(String(x.id))})'>🔒 طلب فتح</button>`;return `<article class="content-card"><div class="cover">${icons[x.type]||'📚'}</div><div class="content-body"><span class="tag">${labels[x.type]||x.type}</span><h3>${window.ELR.escape(x.title)}</h3><p>${window.ELR.escape(x.description||'الزتونة كلها هنا 👌')}</p><div class="meta"><span class="price">${x.is_free?'مجاني':Number(x.price).toFixed(0)+' جنيه'}</span>${action}</div></div></article>`}).join('')||'<p>لا يوجد محتوى في هذا القسم.</p>'}
 document.querySelectorAll('#filters button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.type)});render(new URLSearchParams(location.search).get('type')||'all');
})();
