(async()=>{
 const sb=window.elrfaeySupabase,grid=document.getElementById('contentGrid'); let user=null; let items=[]; let approved=new Set();
 try{const {data}=await sb.auth.getUser();user=data?.user||null;}catch(e){}
 if(user){document.getElementById('contentLogin')?.remove();}
 try{if(user){const {data:purchases}=await sb.from('purchases').select('content_id,status').eq('student_id',user.id);(purchases||[]).filter(x=>x.status==='approved').forEach(x=>approved.add(String(x.content_id)));}}catch(e){console.warn(e)}
 const [cr,er]=await Promise.all([
   sb.from('content').select('id,type,title,description,price,is_free,stage,grade,storage_path,thumbnail_path,external_url,created_at').order('created_at',{ascending:false}),
   sb.from('exams').select('id,title,description,stage,grade,created_at').eq('is_published',true).order('created_at',{ascending:false})
 ]);
 if(cr.error){grid.innerHTML='<div class="empty-state">تعذر تحميل المحتوى حاليًا.</div>';return}
 const normal=cr.data||[];
 const examItems=(er.data||[]).map(x=>({id:'exam-'+x.id,exam_id:x.id,type:'exam',title:x.title,description:x.description,price:0,is_free:false,stage:x.stage,grade:x.grade,created_at:x.created_at}));
 items=[...normal,...examItems].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));
 function youtubeEmbed(url){try{const u=new URL(url);let id=u.searchParams.get('v');if(!id&&u.hostname.includes('youtu.be'))id=u.pathname.slice(1);if(!id&&u.pathname.includes('/shorts/'))id=u.pathname.split('/shorts/')[1].split(/[?&]/)[0];return id?`https://www.youtube.com/embed/${id}?rel=0&modestbranding=1`:null}catch(e){return null}}
 window.openContent=async id=>{
  const item=items.find(x=>String(x.id)===String(id)); if(!item)return;
  if(!user){window.toast('سجّل حسابك الأول عشان تفتح المحتوى.',false);setTimeout(()=>location.href='login.html?next='+encodeURIComponent('content.html?type='+item.type),450);return;}
  if(item.type==='exam'){location.href=`exam.html?id=${item.exam_id}`;return;}
  if(!item.is_free&&!approved.has(String(item.id))){window.toast('المحتوى ده مقفول لحسابك حاليًا.',false);return;}
  if(item.external_url){const emb=item.type==='video'?youtubeEmbed(item.external_url):null;if(emb){const modal=document.createElement('div');modal.className='media-modal';modal.innerHTML=`<div class="media-modal-box"><button class="media-close">×</button><iframe src="${emb}" title="${window.ELR.escape(item.title)}" allow="autoplay; encrypted-media; picture-in-picture" allowfullscreen></iframe></div>`;document.body.appendChild(modal);modal.querySelector('.media-close').onclick=()=>modal.remove();modal.onclick=e=>{if(e.target===modal)modal.remove()};}else if(item.type==='image'){const modal=document.createElement('div');modal.className='media-modal';modal.innerHTML=`<div class="media-modal-box image-box"><button class="media-close">×</button><img src="${window.ELR.escape(item.external_url)}" alt="${window.ELR.escape(item.title)}"></div>`;document.body.appendChild(modal);modal.querySelector('.media-close').onclick=()=>modal.remove();modal.onclick=e=>{if(e.target===modal)modal.remove()};}else location.href=item.external_url;return;}
  if(!item.storage_path){window.toast('المحتوى لا يحتوي على ملف أو رابط.',false);return}
  const {data:s,error:e}=await sb.storage.from('content').createSignedUrl(item.storage_path,600);if(e||!s?.signedUrl){window.toast('تعذر فتح الملف: '+(e?.message||''),false);return}
  if(item.type==='video'){const modal=document.createElement('div');modal.className='media-modal';modal.innerHTML=`<div class="media-modal-box"><button class="media-close">×</button><video controls autoplay playsinline src="${window.ELR.escape(s.signedUrl)}" ${item.thumbnail_path?`poster="${window.ELR.escape(item.thumbnail_path)}"`:''}></video></div>`;document.body.appendChild(modal);modal.querySelector('.media-close').onclick=()=>modal.remove();modal.onclick=e=>{if(e.target===modal)modal.remove()};}else{window.open(s.signedUrl,'_blank');}
 };
 window.requestBuy=async id=>{if(!user){window.toast('سجّل حسابك الأول عشان تطلب فتح المحتوى.',false);setTimeout(()=>location.href='login.html',450);return}const item=items.find(x=>String(x.id)===String(id));if(!item)return;const {error:e}=await sb.from('purchases').upsert({student_id:user.id,content_id:item.id,amount:item.price,status:'pending'},{onConflict:'student_id,content_id'});if(e){window.toast('تعذر إرسال الطلب: '+e.message,false);return}window.toast('تم إرسال طلب فتح المحتوى للإدارة.');approved.delete(String(item.id));render(current)};
 let current='all';function render(type){current=type;const icons={video:'🎥',image:'🖼️',exam:'📝'},labels={video:'فيديو',image:'صورة',exam:'امتحان'};const list=items.filter(x=>type==='all'||x.type===type);grid.innerHTML=list.map(x=>{const unlocked=!!user&&(x.is_free||approved.has(String(x.id)));const locked=!user||(!x.is_free&&!approved.has(String(x.id)));const action=unlocked?`<button class="btn btn-primary small" onclick='openContent(${JSON.stringify(String(x.id))})'>فتح الآن</button>`:`<button class="btn btn-ghost small" onclick='${user?`requestBuy(${JSON.stringify(String(x.id))})`:`openContent(${JSON.stringify(String(x.id))})`}' >🔒 ${user?'طلب فتح':'سجّل لفتح'}</button>`;const thumb=x.thumbnail_path?`<img src="${window.ELR.escape(x.thumbnail_path)}" alt="${window.ELR.escape(x.title)}" loading="lazy">`:x.type==='video'?'🎬':x.type==='image'?'🖼️':'📝';return `<article class="content-card ${locked?'is-locked':''}"><div class="cover ${x.thumbnail_path?'has-thumb':''}">${thumb}<span class="media-play">${x.type==='video'?'▶':''}</span><span class="lock-badge">${locked?'🔒':''}</span></div><div class="content-body"><span class="tag">${labels[x.type]||x.type}</span><h3>${window.ELR.escape(x.title)}</h3><p>${window.ELR.escape(x.description||'الزتونة هنا… بس افتحها بحسابك 😉')}</p><div class="meta"><span class="price">${x.is_free?'مجاني بعد التسجيل':Number(x.price).toFixed(0)+' جنيه'}</span>${action}</div></div></article>`}).join('')||'<div class="empty-state">مفيش محتوى في القسم ده لسه.</div>'}
 document.querySelectorAll('#filters button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.type)});render(new URLSearchParams(location.search).get('type')||'all');
})();
