(async()=>{
 const user=await window.requireAuth();if(!user)return;const sb=window.elrfaeySupabase,id=new URLSearchParams(location.search).get('id');
 const q=document.getElementById('question'),ops=document.getElementById('options'),next=document.getElementById('next'),counter=document.getElementById('counter');
 if(!id){q.textContent='لم يتم تحديد الامتحان.';next.style.display='none';return}
 const {data:existing}=await sb.from('results').select('id,percentage,created_at').eq('exam_id',id).eq('student_id',user.id).limit(1);
 if(existing?.length){q.textContent='أنت امتحنت الامتحان ده قبل كده.';next.style.display='none';const info=document.createElement('p');info.className='already-exam';info.textContent=`نتيجتك السابقة: ${Number(existing[0].percentage).toFixed(1)}%`;q.parentElement?.appendChild(info);return}
 const {data:exam,error:ee}=await sb.from('exams').select('id,title,description').eq('id',id).eq('is_published',true).single();if(ee||!exam){q.textContent='الامتحان غير متاح.';next.style.display='none';return}
 document.querySelector('.exam-card h1').textContent=exam.title;
 const intro=document.createElement('div');intro.className='exam-intro-form';intro.innerHTML=`<h3>بياناتك قبل الامتحان</h3><p>اكتب بياناتك عشان نتيجتك تتسجل بشكل صحيح.</p><input id="examName" placeholder="الاسم" value=""><input id="examPhone" inputmode="tel" placeholder="رقم الهاتف لمعرفة نتيجتك"><button class="btn btn-primary" id="startExam">ابدأ الامتحان</button>`;q.parentElement?.before(intro);q.style.display='none';ops.style.display='none';next.style.display='none';counter.style.display='none';
 const {data:profile}=await sb.from('profiles').select('full_name,phone').eq('id',user.id).single();document.getElementById('examName').value=profile?.full_name||'';document.getElementById('examPhone').value=profile?.phone||'';
 const {data:qs,error:qe}=await sb.rpc('get_exam_questions',{p_exam_id:exam.id});if(qe||!qs?.length){intro.insertAdjacentHTML('beforeend','<p class="bad-text">لا توجد أسئلة في هذا الامتحان حاليًا.</p>');return}
 let started=false,i=0,answers=[];
 document.getElementById('startExam').onclick=async()=>{const name=document.getElementById('examName').value.trim(),phone=document.getElementById('examPhone').value.trim();if(!name||!phone)return window.toast('اكتب الاسم ورقم الهاتف أولًا.',false);const {error:e}=await sb.from('profiles').update({full_name:name,phone}).eq('id',user.id);if(e)return window.toast('تعذر حفظ بياناتك: '+e.message,false);started=true;intro.remove();q.style.display='block';ops.style.display='grid';next.style.display='inline-flex';counter.style.display='block';draw()};
 function draw(){counter.textContent=`السؤال ${i+1} من ${qs.length}`;q.textContent=qs[i].question;ops.innerHTML=(qs[i].options||[]).map((x,n)=>`<button class="option" data-i="${n}">${window.ELR.escape(x)}</button>`).join('');next.disabled=true;ops.querySelectorAll('.option').forEach(b=>b.onclick=()=>{ops.querySelectorAll('.option').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');answers[i]=+b.dataset.i;next.disabled=false})}
 next.onclick=async()=>{if(!started||next.disabled)return;if(i<qs.length-1){i++;draw();return}next.disabled=true;const {data:result,error:e}=await sb.rpc('submit_exam',{p_exam_id:exam.id,p_answers:answers});if(e){next.disabled=false;window.toast(e.message||'تعذر حفظ النتيجة.',false);return}location.href=`result.html?id=${result}`};
})();
