(async()=>{
 const sb=window.elrfaeySupabase;
 const settings={};
 try{const {data}=await sb.from('site_settings').select('data').eq('id',1).single();Object.assign(settings,data?.data||{});}catch(e){console.warn('settings unavailable',e)}
 const setText=(id,v)=>{const el=document.getElementById(id);if(el&&v)el.textContent=v};
 const teacherImg=document.getElementById('teacherPhoto');
 if(teacherImg){
   const candidates=[settings.teacher_image,'assets/images/teacher.jpg','assets/images/teacher.png','assets/images/teacher.webp','assets/images/ahmed.jpg','assets/images/ahmed.png'].filter(Boolean);
   let ti=0;
   const fallback='assets/images/teacher-placeholder.svg';
   const next=()=>{ if(ti<candidates.length){teacherImg.src=candidates[ti++];}else{teacherImg.src=fallback;teacherImg.classList.add('is-placeholder');teacherImg.parentElement.classList.add('photo-placeholder');} };
   teacherImg.onerror=next; next();
 }

 setText('heroTitle',settings.hero_title||'الفيزياء مش حفظ… الفيزياء فهم.');setText('heroSubtitle',settings.hero_subtitle||'افهم القانون، شوف الفكرة، وبعدها الحل هييجي لوحده.');setText('developerPhone',settings.developer_phone||'—');
 const setLink=(id,href,label)=>{const el=document.getElementById(id);if(!el)return;if(href){el.href=href;if(label)el.querySelector('small').textContent=label;}else{el.removeAttribute('href');el.querySelector('small').textContent='غير مضاف بعد';}};
 setLink('teacherContact',settings.teacher_phone?'tel:'+settings.teacher_phone:'',settings.teacher_phone||'غير مضاف');setLink('supportContact',settings.support_phone?'tel:'+settings.support_phone:'',settings.support_phone||'غير مضاف');setLink('whatsappContact',settings.whatsapp,settings.whatsapp?'تواصل مباشرة':'غير مضاف');
 const team=document.getElementById('teamCards');if(team){team.innerHTML=`<article class="team-card helper"><div class="team-icon">🛟</div><div><span>HELPER</span><h3>${window.ELR.escape(settings.helper_name||'HELPER')}</h3><p>${window.ELR.escape(settings.helper_title||'مساعدة ودعم الطلاب')}</p><a class="team-link" href="${settings.helper_phone?'tel:'+window.ELR.escape(settings.helper_phone):'#'}">${window.ELR.escape(settings.helper_phone||'يتم ضبط البيانات من الإدارة')} <i class="fa-solid fa-arrow-left"></i></a></div></article><article class="team-card admin"><div class="team-icon">👑</div><div><span>ADMIN</span><h3>${window.ELR.escape(settings.admin_name||'ADMIN')}</h3><p>${window.ELR.escape(settings.admin_title||'إدارة المنصة')}</p><a class="team-link" href="${settings.admin_phone?'tel:'+window.ELR.escape(settings.admin_phone):'#'}">${window.ELR.escape(settings.admin_phone||'يتم ضبط البيانات من الإدارة')} <i class="fa-solid fa-arrow-left"></i></a></div></article>`}
 if(settings.background_image){document.body.style.setProperty('--custom-bg',`url("${String(settings.background_image).replace(/"/g,'')}")`);document.body.classList.add('custom-bg')}
 try{const {data:{user}}=await sb.auth.getUser();if(user){document.getElementById('homeLogin')?.remove();document.getElementById('homeDashboard').style.display='inline-flex';const {data:p}=await sb.from('profiles').select('role').eq('id',user.id).single();if(p?.role==='admin')document.getElementById('homeAdmin').style.display='inline-flex';}}catch(e){}
 try{const r=await fetch('/api/stats');const d=await r.json();['students','videos','exams'].forEach(k=>{const id=k==='students'?'studentsCount':k==='videos'?'videosCount':'examsCount';const el=document.getElementById(id);if(el)el.textContent=d[k]??0});}catch(e){}
 try{const [cr,er]=await Promise.all([sb.from('content').select('id,type,title,description,is_free,price,thumbnail_path,created_at').order('created_at',{ascending:false}).limit(6),sb.from('exams').select('id,title,description,created_at').eq('is_published',true).order('created_at',{ascending:false}).limit(3)]);const arr=[...(cr.data||[]),...(er.data||[]).map(x=>({...x,type:'exam',is_free:false}))].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)).slice(0,6);const grid=document.getElementById('publicContent');if(grid)grid.innerHTML=arr.map(x=>`<article class="preview-card"><div class="preview-icon ${x.thumbnail_path?'has-thumb':''}">${x.thumbnail_path?`<img src="${window.ELR.escape(x.thumbnail_path)}" alt="${window.ELR.escape(x.title)}" loading="lazy">`:x.type==='video'?'🎥':x.type==='image'?'🖼️':'📝'}<span>🔒</span></div><div><small>${x.type==='video'?'فيديو':x.type==='image'?'صورة':'امتحان'}</small><h3>${window.ELR.escape(x.title)}</h3><p>${window.ELR.escape(x.description||'محتوى جديد على المنصة')}</p><a href="ahmed/content.html?type=${x.type}" class="text-link">شوف التفاصيل <i class="fa-solid fa-arrow-left"></i></a></div></article>`).join('')||'<div class="empty-state">المحتوى هينزل هنا أول ما يبدأ الأستاذ ينشر.</div>';}catch(e){console.warn(e)}
 const box=document.getElementById('chatMessages'),input=document.getElementById('chatInput'),send=document.getElementById('chatSend');
 function answer(msg){const m=msg.toLowerCase();if(m.includes('تسجيل'))return'التسجيل بسيط: اختار طالب، اكتب بياناتك والـ10 خانات بتوع الباسورد، وبعدها تقدر تفتح المحتوى.';if(m.includes('امتحان'))return'الامتحانات بتظهر للطلاب بعد تسجيل الدخول، وكل امتحان بيتحل مرة واحدة وتتسجل نتيجته.';if(m.includes('دعم'))return settings.support_phone?`الدعم الفني: ${settings.support_phone}`:'الدعم الفني متاح من كارت الدعم في أسفل الصفحة.';return'قولّي سؤالك بشكل أوضح وأنا أساعدك في خطوات المنصة. ولو محتاج الإدارة، استخدم كارت HELPER أو ADMIN.'}
 function push(text,who='user'){const d=document.createElement('div');d.className='chat-msg '+who;d.textContent=text;box.appendChild(d);box.scrollTop=box.scrollHeight}
 function sendMsg(text){if(!text.trim())return;push(text,'user');setTimeout(()=>push(answer(text),'bot'),280)}
 send?.addEventListener('click',()=>{sendMsg(input.value);input.value='';input.focus()});input?.addEventListener('keydown',e=>{if(e.key==='Enter'){sendMsg(input.value);input.value=''}});document.querySelectorAll('.quick-replies button').forEach(b=>b.addEventListener('click',()=>sendMsg(b.dataset.msg)));
 const musicBtn=document.getElementById('musicBtn'),music=document.getElementById('bgMusic');let on=false;musicBtn?.addEventListener('click',async()=>{on=!on;if(on){if(music){music.volume=.10;try{await music.play()}catch(e){}}musicBtn.innerHTML='<i class="fa-solid fa-volume-high"></i>'}else{music?.pause();musicBtn.innerHTML='<i class="fa-solid fa-volume-xmark"></i>'}});
})();
