function json(res,status,body){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(body));}
async function sbFetch(path,options={}){const base=process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!base||!key)throw new Error('Server is not configured.');const headers=Object.assign({apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json'},options.headers||{});return fetch(`${base}${path}`,Object.assign({},options,{headers}));}
async function verifyUser(token){if(!token)throw new Error('Unauthorized');const r=await sbFetch('/auth/v1/user',{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error('Unauthorized');const u=await r.json();const p=await sbFetch(`/rest/v1/profiles?id=eq.${encodeURIComponent(u.id)}&select=id,full_name,role,stage,grade,phone&limit=1`);const rows=await p.json().catch(()=>[]);return {user:u,profile:rows[0]};}
function webhookFor(settings,type){const d=settings.data||{};if(type==='registration')return d.discord_webhook_registrations||d.discord_webhook||'';if(type==='video_view')return d.discord_webhook_videos||'';if(type==='image_view')return d.discord_webhook_images||'';if(type.startsWith('exam_')||type==='exam_result')return d.discord_webhook_exams||'';return d.discord_webhook_admin||d.discord_webhook||'';}
async function postWebhook(url,payload){if(!url)return false;const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});return r.ok;}
async function discordFetch(path,options={}){const token=process.env.DISCORD_BOT_TOKEN;if(!token)throw new Error('DISCORD_BOT_TOKEN is missing');const headers=Object.assign({Authorization:`Bot ${token}`,'Content-Type':'application/json'},options.headers||{});return fetch(`https://discord.com/api/v10${path}`,Object.assign({},options,{headers}));}
module.exports=async(req,res)=>{try{const token=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');const {user,profile}=await verifyUser(token);const action=String(req.query?.action||'log');if(action==='log'){
 if(!profile)return json(res,403,{error:'Profile not found'});const body=typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{});const type=String(body.event_type||'');const settingsRes=await sbFetch('/rest/v1/site_settings?id=eq.1&select=data&limit=1');const settingsRows=await settingsRes.json().catch(()=>[]);const url=webhookFor(settingsRows[0]||{},type);if(!url)return json(res,200,{ok:true,skipped:true});const d=body.details||{};const names={video_view:'مشاهدة فيديو',image_view:'مشاهدة صورة',exam_open:'فتح امتحان',exam_start:'بدء امتحان',exam_submit_start:'تسليم امتحان',exam_result:'نتيجة امتحان'};const embed={title:`📌 ${names[type]||type}`,description:`**الطالب:** ${profile.full_name||'—'}\n**الهاتف:** ${profile.phone||'—'}\n**Discord:** ${user.email?'مرتبط بحساب الموقع':'—'}`,fields:Object.entries(d).slice(0,8).map(([k,v])=>({name:k,value:String(v).slice(0,900)||'—',inline:true})),timestamp:new Date().toISOString()};const ok=await postWebhook(url,{embeds:[embed]});return json(res,200,{ok});}
if(action==='sync-members'){
 if(profile?.role!=='admin')return json(res,403,{error:'Admin only'});const body=typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{});const settingsRes=await sbFetch('/rest/v1/site_settings?id=eq.1&select=data&limit=1');const rows=await settingsRes.json().catch(()=>[]);const data=rows[0]?.data||{};const guild=String(body.guild_id||data.discord_guild_id||'').trim();const webhook=data.discord_webhook_members||'';if(!guild||!webhook)return json(res,400,{error:'أضف Guild ID وWebhook روم الأعضاء أولًا.'});let after='0',count=0,rounds=0;while(rounds<20){const r=await discordFetch(`/guilds/${encodeURIComponent(guild)}/members?limit=1000&after=${encodeURIComponent(after)}`);if(!r.ok){const t=await r.text();return json(res,400,{error:'Discord رفض قراءة الأعضاء. تأكد من Bot Token وServer Members Intent.'})}const members=await r.json();if(!Array.isArray(members)||!members.length)break;const chunks=[];for(let i=0;i<members.length;i+=20)chunks.push(members.slice(i,i+20));for(const chunk of chunks){const lines=chunk.map(m=>`• ${m.user?.username||'unknown'} — ${m.user?.id||''}`).join('\n');await postWebhook(webhook,{embeds:[{title:'👥 مزامنة أعضاء Discord',description:lines.slice(0,3900),footer:{text:`${chunk.length} عضو`},timestamp:new Date().toISOString()}]});count+=chunk.length;}after=members[members.length-1]?.user?.id||after;if(members.length<1000)break;rounds++;}return json(res,200,{message:`تمت مزامنة ${count} عضو من Discord.`});}
return json(res,400,{error:'Unknown action'});
}catch(e){console.error(e);return json(res,e.message==='Unauthorized'?401:500,{error:e.message||'Discord error'});}};
